### ISSUE TITLE
Sugestão de novo guia

### ISSUE THREAD

**Issue by andyalmeida** [lizianefelix/refs-in-tech#3]
Seria interessante também um quia com canais de live coders, uma modalidade que tem crescido bastante ultimamente e tem bastante conteúdo bacana :)

**Comment by lizianefelix** [comment]
Oi @andyalmeida!
Verdade, seria uma boa. Poderia adicionar um PR com essa nova seção e também alguma referência se tiver?

**Comment by andyalmeida** [comment]
Opa, claro, posso sim, conheço alguns. Vou criar essa guia e abro a PR.

**Comment by lizianefelix** [comment]
Ótimo, @andyalmeida!
